version: '3.8'

services:
  palworld:
    image: kagurazakanyaa/palworld
    env_file:
      - .env
    ports:
      - "${GAME_PORT}:${GAME_PORT}"
      - "${RCON_PORT}:${RCON_PORT}"
    restart: unless-stopped
    #volumes:
    #  -palworld_data:/opt/palworld/Pal/Saved
