version: '3.8'

services:
  palworld:
    image: kagurazakanyaa/palworld
    environment:
      - IS_PUBLIC=false
      - ADMIN_PASSWORD=MyRCONPassword
      - RCON_ENABLED=true
    ports:
      - "25575:25575"
    #volumes:
    #  -palworld_data:/opt/palworld/Pal/Saved
